### ISSUE TITLE
Unable to set DoH or Custom DoH provider after network reset.

### ISSUE THREAD

**Issue by agpt8** [HotCakeX/WinSecureDNSMgr#7]
Hi there,

I recently reset my network on my workstation using the following commands:
```text
ipconfig.exe /release
ipconfig.exe /flushdns
ipconfig.exe /renew
netsh.exe winsock reset
netsh.exe interface ipv4 reset
netsh.exe interface ipv6 reset
netsh.exe interface ip delete destinationcache
```

After restarting the device, I wanted to add a custom DoH provider. So I used the following command:
`Set-CDOH -DoHTemplate https://dns11.quad9.net/dns-query -IPV4s 9.9.9.11, 149.112.112.11 -IPV6s 2620:fe::11, 2620:fe::fe:11`

_PS: I dont think this is a template issue as this command worked fine before._

But I got this error:
![image](https://github.com/HotCakeX/WinSecureDNSMgr/assets/16762897/4608853c-9fe8-4b64-a89d-2d531d8407a9)

I also tried to add a predefined one but got the same error (screenshot above) for this command as well: `Set-DOH -DoHProvider Quad9`

The errors themselves arent very helpful. Where can I get the stacktrace for this?

Any clues why this might be happening? This is on latest beta build 22635.3790.

**Comment by agpt8** [comment]
Apparently, if you trun off dns caching, either through services (DNS Client > Disabled) or through regedit (HKLM > System > CurrentControlSet > Services > Dnscache > Start > set to 4, which in turn does not allow changing the properties through services panel in MMC anymore), the above error would show up.

Enabling it through regedit (setting it to 2) or setting it to automatic in services panel and restarting the PC would resolve the above issue!

Using admin powershell or cmd to register dns (`ipconfig /registerdns`) or `Clear-DnsClientCache` would not work if dnscache is changed from regedit.

Is there a way to make the errors more descriptive? Maybe mentioning if any required component (dns client in this case) is either not accessible or is disabled.

**Comment by HotCakeX** [comment]
Thanks for finding out the reason for that error. In the latest update i added a check to make sure that service's startup type is not set to disabled and if it is then display a proper error.
